#!/bin/bash
#PBS -l select=6:system=polaris
#PBS -l walltime=01:00:00
#PBS -N aps-mini-apps
#PBS -q debug-scaling

#file systems used by the job
#PBS -l filesystems=home:eagle

#Project name
#PBS -A diaspora

#set -euo pipefail

# Key Exp parameters, change these parameters to generate data
# Time to relaunch a new task manager after terminating one
recover_interval=1
# Number of reconstruction processes (consumer/main computation tasks)
# num_sirts=(2 4 8 16)
num_sirts=(8)
# Mean time between failures
# failure_periods=(160 80 40 20)
failure_periods=(1000000 160 80 40 20)
# Failure modes:
#   - periodic: failures happen once every a fixed interval
#   - singe:    failure happen only once
#   - random:   failures happen with a varied period, generated by an exponential variable
failure_modes=(periodic random)

ckpt_freq=0

# --- tiny helper: update ntask_sirt in a JSON file using jq (atomic write)

DIR="$HOME/diaspora/src/aps-mini-apps"
echo "DIR: $DIR"

TOP="$(cat "$DIR/recent-run")"

# # optional: ensure we clean up the cluster if something fails mid-loop
# cleanup_cluster() {
#   # best-effort stop if the script dies in the middle
#   if [[ -x "$WORKSPACE/test-failure.sh" ]]; then
#     (cd "$WORKSPACE" && bash test-failure.sh) || true
#   fi
# }
# trap cleanup_cluster EXIT

# Set up compoenents
cd $TOP/aps-mini-apps
bash setup.sh

ccount=0
for num_sirt in "${num_sirts[@]}"; do
  for failure_period in "${failure_periods[@]}"; do
    for failure_mode in "${failure_modes[@]}"; do

      num_task=$(( num_sirt * 2 ))
      num_sinogram=$(( num_sirt * 2 ))
      
      echo bash polaris-exec-pipeline.sh \
          $num_sirt \
          $num_task \
          $num_sinogram \
          $failure_mode \
          $failure_period \
          0 \
          true \
          $ckpt_freq > build/logs/latest/cmd-$count

      bash polaris-exec-pipeline.sh \
          $num_sirt \
          $num_task \
          $num_sinogram \
          $failure_mode \
          $failure_period \
          0 \
          true \
          $ckpt_freq
      # sleep 1
    count=$((count + 1))
    done
  done
done
