#!/bin/bash
#PBS -l select=6:system=polaris
#PBS -l walltime=01:00:00
#PBS -N aps-mini-apps
#PBS -q debug-scaling

#file systems used by the job
#PBS -l filesystems=home:eagle

#Project name
#PBS -A diaspora

#set -euo pipefail

# Key Exp parameters, change these parameters to generate data
# Time to relaunch a new task manager after terminating one
recover_interval=1
num_tasks_per_sirt=1
num_sinogram_per_task=1
# Number of reconstruction processes (consumer/main computation tasks)
num_sirts=(2)
# Mean time between failures
failure_periods=(10000000 1000 100)
# failure_periods=(5)
# Failure modes:
#   - periodic: failures happen once every a fixed interval
#   - singe:    failure happen only once
#   - random:   failures happen with a varied period, generated by an exponential variable
failure_modes=(periodic)
slowdowns=(1000)
#failure_modes=(periodic)

ckpt_freq=0

# --- tiny helper: update ntask_sirt in a JSON file using jq (atomic write)

DIR="$HOME/diaspora/src/aps-mini-apps"
echo "DIR: $DIR"

TOP="$(cat "$DIR/recent-run")"

# # optional: ensure we clean up the cluster if something fails mid-loop
# cleanup_cluster() {
#   # best-effort stop if the script dies in the middle
#   if [[ -x "$WORKSPACE/test-failure.sh" ]]; then
#     (cd "$WORKSPACE" && bash test-failure.sh) || true
#   fi
# }
# trap cleanup_cluster EXIT

# Set up compoenents
cd $TOP/aps-mini-apps
bash setup.sh



count=0
for slowdown in "${slowdowns[@]}"; do
  for num_sirt in "${num_sirts[@]}"; do
    for failure_period in "${failure_periods[@]}"; do
      for failure_mode in "${failure_modes[@]}"; do

        cp slow_down_$slowdown.txt slow_down_samples.txt
        slowdownindex=1

        num_task=$(( num_sirt * num_tasks_per_sirt ))
        num_sinogram=$(( num_task * num_sinogram_per_task ))
        per_worker_failure_period=$(( failure_period / num_sirt ))
        
        bash exec-pipeline.sh \
            $num_sirt \
            $num_task \
            $num_sinogram \
            $failure_mode \
            $per_worker_failure_period \
            $slowdownindex \
            true \
            $ckpt_freq
        # sleep 1

        echo bash exec-pipeline.sh \
            $num_sirt \
            $num_task \
            $num_sinogram \
            $failure_mode \
            $per_worker_failure_period \
            $slowdownindex \
            true \
            $ckpt_freq > build/logs/latest/cmd-$count
        count=$((count + 1))
      done
    done
  done
done

