#!/bin/bash
#PBS -l select=1:system=polaris
#PBS -l walltime=01:00:00
#PBS -N Flink
#PBS -q debug-scaling

#file systems used by the job
#PBS -l filesystems=home:eagle

#Project name
#PBS -A diaspora

# set -euo pipefail

# Key Exp parameters, change these parameters to generate data
# Time to relaunch a new task manager after terminating one
recover_interval=1
# Number of reconstruction processes (consumer/main computation tasks)
num_sirts=(2)
task_per_sirts=(1 2 4 8)
# Mean time between failures
ckpt_freqs=(1 2 4 8)
# Failure modes:
#   - periodic: failures happen once every a fixed interval
#   - singe:    failure happen only once
#   - random:   failures happen with a varied period, generated by an exponential variable
# failure_modes=(periodic random)
failure_mode=periodic
failure_period=10000000

# --- tiny helper: update ntask_sirt in a JSON file using jq (atomic write)

# DIR="$HOME/diaspora/src/aps-mini-apps"
DIR=`pwd`
echo "DIR: $DIR"

TOP=$DIR

# # optional: ensure we clean up the cluster if something fails mid-loop
# cleanup_cluster() {
#   # best-effort stop if the script dies in the middle
#   if [[ -x "$WORKSPACE/test-failure.sh" ]]; then
#     (cd "$WORKSPACE" && bash test-failure.sh) || true
#   fi
# }
# trap cleanup_cluster EXIT

# Set up compoenents
cd $DIR
bash setup.sh

count=0
for num_sirt in "${num_sirts[@]}"; do
  for task_per_sirt in "${task_per_sirts[@]}"; do
    for ckpt_freq in "${ckpt_freqs[@]}"; do
      num_task=$(( num_sirt * task_per_sirt ))
      num_sinogram=$(( num_sirt * task_per_sirt ))
      
      echo bash exec-pipeline.sh \
          $num_sirt \
          $num_task \
          $num_sinogram \
          $failure_mode \
          $failure_period \
          0 \
          true \
          $ckpt_freq
      # sleep 1

      echo bash exec-pipeline.sh \
          $num_sirt \
          $num_task \
          $num_sinogram \
          $failure_mode \
          $failure_period \
          0 \
          true \
          $ckpt_freq >> build/logs/latest/cmd-$count
    count=$((count + 1))
    done
  done
done

