# automatically generated by the FlatBuffers compiler, do not modify

# namespace: TraceDS

class IType(object):
    End = 0
    Projection = 1
    White = 2
    Dark = 3
    WhiteReset = 4
    DarkReset = 5

