# automatically generated by the FlatBuffers compiler, do not modify

# namespace: TraceDS

import flatbuffers

class Dim2(object):
    __slots__ = ['_tab']

    # Dim2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Dim2
    def Y(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Dim2
    def X(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateDim2(builder, y, x):
    builder.Prep(4, 8)
    builder.PrependInt32(x)
    builder.PrependInt32(y)
    return builder.Offset()
